const crypto = require("crypto")
const request = require("supertest")
const SIMPLE_BOOKS_API_BASE_URL = "https://simple-books-api.glitch.me"

async function generateAccessToken() {
  const uniqueId = crypto.randomBytes(16).toString("hex")
  console.log(
    `Note: new uniqueId generated by crypto -> uniqueId="${uniqueId}"`
  )
  const body = {
    clientName: `${uniqueId}`,
    clientEmail: `${uniqueId}@email.com`,
  }

  const authResponse = await request(SIMPLE_BOOKS_API_BASE_URL)
    .post("/api-clients")
    .set("Content-Type", "application/json")
    .send(body)

  if (authResponse.status === 201) {
    console.log(
      `New accessToken "${
        authResponse.body.accessToken
      }" is successfully generated for client: ${JSON.stringify(body)}.`
    )
    return authResponse.body.accessToken
  } else {
    throw Error(
      `Failed to register API client. POST /api-clients responded with ${
        authResponse.status
      } ${JSON.stringify(authResponse.body)}`
    )
  }
}

module.exports = { generateAccessToken: generateAccessToken }
